appName: sonarr
namespace: mediafactory

image:
  repository: linuxserver/sonarr
  tag: 3.0.9
  imagePullPolicy: IfNotPresent

env:
  TZ: America/Chicago
  PGID: 568
  PUID: 568

ingress:
  host: sonarr.example.com

service:
  port: 8989

persistence:
  config:
    hostPath: /home/apps/sonarr
    mountPath: /config
  backups:
    hostPath: /mnt/nas/backups/sonarr
    mountPath: /backups
  movies:
    hostPath: /mnt/nas/series
    mountPath: /media/series
  downloads: 
    hostPath: /mnt/nas/downloads
    mountPath: /downloads
  complete:
    hostPath: /mnt/nas/complete
    mountPath: /complete

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 4000m
    memory: 2000Mi