appName: sonarr
namespace: mediafactory

image:
  repository: linuxserver/sonarr
  tag: 4.0.11.2680-ls261
  imagePullPolicy: IfNotPresent

env:
  TZ: America/Chicago
  PGID: 568
  PUID: 568

ingress:
  host: sonarr.example.com

service:
  port: 8989

persistence:
  config:
    hostPath: 
    mountPath: /config
  backups:
    enabled: false
    existingClaim: 
    mountPath: /backups
  series:
    existingClaim: 
    mountPath: /media/series
  downloads: 
    hostPath: 
    mountPath: /downloads
  complete:
    enabled: false
    hostPath: 
    mountPath: /complete
  customServices:
    enabled: false
    hostPath:
    mountPath: /custom-services.d
  customContInit:
    enabled: false
    hostPath:
    mountPath: /custom-cont-init.d

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 4000m
    memory: 2000Mi