apiVersion: v2
name: wizarr
description: Wizarr is an advanced user invitation and management system for Jellyfin, Plex, Emby etc.
appVersion: "2025.6.3"
type: application
version: 0.6.6
keywords:
  - wizarr
  - invitation
  - pvr
  - mediafactory
  - torrent
  - usenet
maintainers:
  - name: GenericEric
    email: eric@bgeneric.net
    url: https://bgeneric.net
