appName: wizarr
namespace: mediafactory

image:
  repository: ghcr.io/wizarrrr/wizarr
  tag: 2025.8.1
  imagePullPolicy: IfNotPresent

env:
  TZ: America/Chicago
  PGID: 568
  PUID: 568

ingress:
  host: wizarr.example.com

service:
  port: 5690

persistence:
  config:
    hostPath: 
    mountPath: /data/database
  backups:
    enabled: false
    existingClaim: 
    mountPath: /backups

resources:
  requests:
    cpu: 100m
    memory: 60Mi
  limits:
    cpu: 4000m
    memory: 2000Mi