apiVersion: v2
name: lidarr
description: Lidarr is a music collection manager for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new tracks from your favorite artists and will grab, sort and rename them.
appVersion: "2.13.3"
type: application
version: 0.7.0
keywords:
  - lidarr
  - music
  - pvr
  - mediafactory
  - torrent
  - usenet
maintainers:
  - name: GenericEric
    email: eric@bgeneric.net
    url: https://bgeneric.net
