appName: lidarr
namespace: mediafactory

image:
  repository: linuxserver/lidarr
  tag: 2.2.5.4141-ls167
  imagePullPolicy: IfNotPresent

env:
  TZ: America/Chicago
  PGID: 568
  PUID: 568

ingress:
  host: lidarr.example.com

service:
  port: 8686

persistence:
  config:
    hostPath: 
    mountPath: /config
  backups:
    enabled: false
    existingClaim: 
    mountPath: /backups
  music:
    existingClaim: 
    storageClass:
    mountPath: /media/music
  downloads: 
    hostPath: 
    mountPath: /downloads
  complete:
    enabled: false
    hostPath: 
    mountPath: /complete
  customServices:
    enabled: false
    hostPath:
    mountPath: /custom-services.d
  customContInit:
    enabled: false
    hostPath:
    mountPath: /custom-cont-init.d

resources:
  requests:
    cpu: 100m
    memory: 60Mi
  limits:
    cpu: 4000m
    memory: 2000Mi