appName: lidarr
namespace: mediafactory

image:
  repository: linuxserver/lidarr
  tag: 1.0.2
  imagePullPolicy: IfNotPresent

env:
  TZ: America/Chicago
  PGID: 568
  PUID: 568

ingress:
  host: lidarr.example.com

service:
  port: 8686

persistence:
  config:
    hostPath: /home/apps/lidarr
    mountPath: /config
  backups:
    hostPath: /mnt/nas/backups/lidarr
    mountPath: /backups
  music:
    hostPath: /mnt/nas/music
    mountPath: /media/music
  downloads: 
    hostPath: /mnt/nas/downloads
    mountPath: /downloads
  complete:
    hostPath: /mnt/nas/complete
    mountPath: /complete

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 4000m
    memory: 2000Mi