appName: readarr
namespace: mediafactory

image:
  repository: linuxserver/readarr
  tag: nightly-0.3.27.2532-ls302
  imagePullPolicy: IfNotPresent

env:
  TZ: America/Chicago
  PGID: 568
  PUID: 568

ingress:
  host: readarr.example.com

service:
  port: 8787

persistence:
  config:
    hostPath: 
    mountPath: /config
  backups:
    enabled: false
    existingClaim: 
    mountPath: /backups
  books:
    existingClaim: 
    mountPath: /media/books
  downloads: 
    hostPath: 
    mountPath: /downloads
  complete:
    enabled: false
    hostPath: 
    mountPath: /complete

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 4000m
    memory: 2000Mi