apiVersion: v2
name: flaresolverr
description: FlareSolverr is a proxy server to bypass Cloudflare protection 
appVersion: "3.3.24"
type: application
version: 0.5.8
keywords:
  - flaresolverr
  - cloudflare
  - proxy
  - mediafactory
  - torrent
  - usenet
maintainers:
  - name: GenericEric
    email: eric@bgeneric.net
    url: https://bgeneric.net
