appName: requestrr
namespace: mediafactory

image:
  repository: linuxserver/requestrr
  tag: V2.1.2-ls44
  imagePullPolicy: IfNotPresent

env:
  TZ: America/Chicago
  PGID: 568
  PUID: 568

ingress:
  host: requestrr.example.com

service:
  port: 4545

persistence:
  config:
    hostPath: /home/apps/requestrr
    mountPath: /config
  backups:
    enabled: false
    existingClaim: 
    mountPath: /backups

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 4000m
    memory: 2000Mi