appName: headphones
namespace: mediafactory

image:
  repository: linuxserver/headphones
  tag: version-a78f38c1
  imagePullPolicy: IfNotPresent

env:
  TZ: America/Chicago
  PGID: 568
  PUID: 568

ingress:
  host: headphones.example.com

service:
  port: 8181

persistence:
  config:
    hostPath: 
    mountPath: /config
  backups:
    enabled: false
    existingClaim: 
    mountPath: /backups
  music:
    existingClaim: 
    storageClass:
    mountPath: /media/music
  downloads: 
    hostPath: 
    mountPath: /downloads/downloads
  complete:
    enabled: false
    hostPath: 
    mountPath: /downloads/complete

resources:
  requests:
    cpu: 100m
    memory: 60Mi
  limits:
    cpu: 4000m
    memory: 2000Mi