appName: qbittorrent
namespace: mediafactory

image:
  repository: dyonr/qbittorrentvpn
  tag: latest
  imagePullPolicy: IfNotPresent

env:
  TZ: America/Chicago
  PGID: 568
  PUID: 568

vpn:
  VPN_ENABLED: yes
  LAN_NETWORK: 10.10.10.0/24,192.168.0/24
  NAME_SERVERS: 1.1.1.1,1.0.0.1
  HEALTH_CHECK_HOST: one.one.one.one
  HEALTH_CHECK_INTERVAL: 300

ingress:
  host: qbittorrent.example.com

service:
  port: 8080

persistence:
  config:
    hostPath: /home/apps/qbittorrent
    mountPath: /config
  backups:
    enabled: false
    existingClaim: 
    mountPath: /backups
  downloads: 
    hostPath: /mnt/nas/downloads
    mountPath: /downloads
  complete:
    enabled:
    hostPath: /mnt/nas/complete
    mountPath: /complete

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 4000m
    memory: 2000Mi