appName: unpackerr
namespace: mediafactory

image:
  repository: hotio/unpackerr
  tag: release-bcb845c
  imagePullPolicy: IfNotPresent

env:
  TZ: America/Chicago

radarr:
  enabled: false
  URL: http://radarr.mediafactory.svc.cluster.local:7878
  API_KEY: 
  PATHS: /complete/movies
  DELETE_DELAY: 60m
  PROTOCOLS: torrent
radarr2:
  enabled: false
  URL:
  API_KEY:
  PATHS:
  DELETE_DELAY:
  PROTOCOLS:
sonarr:
  enabled: false
  URL: http://sonarr.mediafactory.svc.cluster.local:8989
  API_KEY:
  PATHS: /complete/series
  DELETE_DELAY:
  PROTOCOLS: torrent
sonarr2:
  enabled: false
  URL:
  API_KEY:
  PATHS:
  DELETE_DELAY:
  PROTOCOLS:
lidarr:
  enabled: false
  URL: http://lidarr.mediafactory.svc.cluster.local:8686
  API_KEY:
  PATHS: /complete/music
  DELETE_DELAY:
  PROTOCOLS: torrent
lidarr2:
  enabled: false
  URL:
  API_KEY:
  PATHS:
  DELETE_DELAY:
  PROTOCOLS:
readarr:
  enabled: false
  URL: http://readarr.mediafactory.svc.cluster.local:8787
  API_KEY:
  PATHS: /complete/books
  DELETE_DELAY:
  PROTOCOLS: torrent
readarr2:
  enabled: false
  URL:
  API_KEY:
  PATHS:
  DELETE_DELAY:
  PROTOCOLS:

persistence:
  config:
    enabled: false
    hostPath: 
    mountPath: /config
  movies:
    hostPath: 
    mountPath: /complete/movies
  series:
    hostPath: 
    mountPath: /complete/series
  music:
    hostPath: 
    mountPath: /complete/music
  books:
    hostPath: 
    mountPath: /complete/books
  downloads:
    enabled: false
    hostPath:
    mountPath:
  

service:
  port: 8989

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 6000m
    memory: 2000Mi