appName: jellyseerr
namespace: mediafactory

image:
  repository: fallenbagel/jellyseerr
  tag: 2.7.2
  imagePullPolicy: IfNotPresent

env:
  TZ: America/Chicago
  PGID: 568
  PUID: 568

database:
  sqlite:
    enabled: true
    logQueries: false
  postgresql:
    enabled: false
    host: "127.0.0.1"
    port: "5432"
    user: "jellyseerr"
    password: "securepassword"
    dbName: "jellyseerr"
    logQueries: "false"

ingress:
  host: jellyseerr.example.com

service:
  port: 5055

persistence:
  config:
    hostPath: 
    mountPath: /config
  backups:
    enabled: false
    existingClaim: 
    mountPath: /backups

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 4000m
    memory: 2000Mi