appName: radarr
namespace: mediafactory

image:
  repository: linuxserver/radarr
  tag: 5.26.2.10099-ls277
  imagePullPolicy: IfNotPresent

env:
  TZ: America/Chicago
  PGID: 568
  PUID: 568

ingress:
  host: radarr.example.com

service:
  port: 7878

persistence:
  config:
    hostPath: 
    mountPath: /config
  backups:
    enabled: false
    existingClaim: 
    mountPath: /backups
  movies:
    existingClaim: 
    mountPath: /media/movies
  downloads: 
    hostPath: 
    mountPath: /downloads
  complete:
    enabled: false
    hostPath: 
    mountPath: /complete
  customServices:
    enabled: false
    hostPath:
    mountPath: /custom-services.d
  customContInit:
    enabled: false
    hostPath:
    mountPath: /custom-cont-init.d

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 4000m
    memory: 2000Mi