appName: prowlarr
namespace: mediafactory

image:
  repository: linuxserver/prowlarr
  tag: 1.2.2.2699-ls6
  imagePullPolicy: Always

env:
  TZ: America/Chicago
  PGID: 568
  PUID: 568

ingress:
  host: prowlarr.example.com

service:
  port: 9696

persistence:
  config:
    hostPath: /home/apps/prowlarr
    mountPath: /config
  backups:
    hostPath: /mnt/nas/backups/prowlarr
    mountPath: /backups

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 4000m
    memory: 2000Mi