appName: prowlarr
namespace: mediafactory

image:
  repository: linuxserver/prowlarr
  tag: 1.20.1.4603-ls79
  imagePullPolicy: Always

env:
  TZ: America/Chicago
  PGID: 568
  PUID: 568

ingress:
  host: prowlarr.example.com

service:
  port: 9696

persistence:
  config:
    hostPath: 
    mountPath: /config
  backups:
    enabled: false
    existingClaim: 
    mountPath: /backups

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 4000m
    memory: 3000Mi