appName: sabnzbdvpn
namespace: mediafactory

image:
  repository: binhex/arch-sabnzbdvpn
  tag: 4.2.3-1-06
  imagePullPolicy: IfNotPresent

env:
  TZ: America/Chicago
  PGID: 568
  PUID: 568

vpn:
  VPN_ENABLED: yes
  ENABLE_PRIVOXY: yes
  VPN_PROV: custom
  VPN_CLIENT: wireguard
  STRICT_PORT_FORWARD: yes
  LAN_NETWORK: 10.10.10.0/24,192.168.0/24
  NAME_SERVERS: 1.1.1.1,1.0.0.1


ingress:
  host: sabnzbdvpn.example.com

service:
  port: 8080

persistence:
  config:
    hostPath: /home/apps/sabnzbd
    mountPath: /config
  backups:
    enabled: false
    existingClaim: 
    mountPath: /backups
  downloads: 
    hostPath: /mnt/nas/downloads
    mountPath: /downloads
  complete:
    enabled: false
    hostPath: /mnt/nas/complete
    mountPath: /complete

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 4000m
    memory: 2000Mi